### ISSUE TITLE
RoboRIO Hardknott

### ISSUE THREAD

**Issue by RyanHir** [ni/nilrt#114]
Hello,

I have noticed that commits such as 7143fec29492f64262ec206f9e8a5cad7714baf4 are hard-coding x64, does this mean that the RoboRIO v1 and v2 are going to stay on Sumo for the long term? I was hoping to see the compiler version eventually be bumped to GCC 10 for FRC usage.

**Comment by jeminor** [comment]
Hi @RyanHir 

As you've noticed from recent commits, our priority at the moment is to get the x64-based kernel and distribution up-to-date. As such, we will be treating these as separate code bases and prioritizing upgrades independently. At the moment we can't pass along a date for when the distribution would be upgraded for that target, but feel free to pass along the needs you are encountering so we can take that into consideration.

**Comment by RyanHir** [comment]
I have been talking to the maintainers of [WPILib](https://github.com/wpilibsuite), and we are considering uploading our own build of libgcc and libstdc++ to the RoboRIO. From testing on an Ubuntu 18.04 VM with the GCC 11 runtime, this appears possible. GCC has ensured that the runtime libraries can still execute binaries built against the older runtime/compiler, so the operating system should still work. While it would be preferable to build against artifacts built by NI, this will probably be the easiest way forward.

Are there any reasons to stray away from this plan, such as compatibility with LabView or downstream GCC patches?

**Comment by jeminor** [comment]
I have discussed this with the team internally, and while it may work it would be outside of the box of what NI can officially support.  That being said, we didn't envision any significant obstacles based on just what you've said here.

Have you given this a try already, and if so did that seem to work?

**Comment by RyanHir** [comment]
No tests have been made on the RoboRIO, so I can't say anything about stability for this exact scenario. However, tests with an Ubuntu 18.04 machine has shown that this is possible. We were able to build the runtime libraries and make them default via `LD_LIBRARY_PATH` and we did not notice any system instability. Products such as Firefox and Chromium were tested with our runtime.

You can recreate similar results by enabling this PPA https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test and installing gcc-11 and g++-11 which will bring in newer runtime libraries for the system. By installing these packages, the original runtime is replaced just like what we are planning to do.

**Comment by jeminor** [comment]
Thanks for that update!

I'm going to close this issue since the initial question was answered, feel free to ping back if you don't feel like that action is appropriate.
