### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by mxrmesulog** [ni/nilrt#13]
Hello,

I'm trying to build an image to make it run on Zynq 7020 (Pynq Z2 or PynqBerry).
I'm facing an issue when trying to build.

I'm a newbie in this, but I just follow the steps and fix many depencencies, but this one, I did'nt find the solution :

| ../../glib-2.54.3/gio/gdbusauth.c: In function ‘_g_dbus_auth_run_server’:
| ../../glib-2.54.3/gio/gdbusauth.c:1305:11: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
|  1305 |           debug_print ("SERVER: WaitingForBegin, read '%s'", line);
|       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I have setup the tools Ubuntu 20.14 VM using Virtualbox. Do you recommend another Linux distribution ?
I have tried in different branches 17.0, 18. and master barnch and for x86 or ARM build.

Trying to build the Python package failed at the same step. I found a forum saying that the I need to removed the argument in the specific file or appmly a patch on a specific tool, but I'm just want to see if you have any recommandation to make it more straightforward.

Best regards

**Comment by shruthi-ravi** [comment]
Hello,

Unfortunately, we do not support the Zynq boards you mentioned, and have not tested our software on them. Also, if your goal is to use these boards with MAX or LabVIEW, the image generated here is incomplete for that purpose and missing binaries that are added on as part of our internal build process. 
You could try posting in one of the Xilinx community [forums](https://forums.xilinx.com/) for alternative software suggestions. 

That said, re: the build errors, the Ubuntu distribution you are using might be too new. We recommend the Debian (stretch or buster) distribution and using our latest release branch - [nilrt/20.0/sumo](https://github.com/ni/nilrt/tree/nilrt/20.0/sumo) to build an image. We also have a Dockerfile that you could use to set up a Docker container with a specific build environment to build images within. Please take a look at the [instructions](https://github.com/ni/nilrt/tree/nilrt/20.0/sumo#creating-a-docker-build-container). I hope this helps.

**Comment by mxrmesulog** [comment]
Hello,

Thanks for the reply. I know that this board is not supported by NI. In my mind, this is the purpose of this repository. Give ability to users to build something based on that system for unsupported hardware.

Yes my idea was to build something that can start on that board and that I can programm with LabVIEW Real-Time even if the OS is not real-time capable due to my specific build. I love LabVIEW and I have a Pynq board on my desk.

For the build process, I moved to debian, and the build passed. Not so direct, but much more better than with Ubuntu. I will try with the docker image. I first missunderstand this point, that why I didn't try it, but, yes, this is the best solution to build it.

but, at the end, if the image doesn't provide the LabVIEW Real-Time Runtime and ability to install software from MAX. I don't really understand the purpose of this git repository.

Best regards.

**Comment by shruthi-ravi** [comment]
Hi,

I'm sorry that the image generated by this repo does not serve your needs. To be clear, the purpose of this repo is to aid users in building custom ipks that they can install on top of an NI LinuxRT image that is already installed on a device.

However, there is another way that can possibly get you further in your goal. There is a [layer](https://github.com/MakerHub/meta-labview) that provides LabVIEW Runtime in a chroot environment for embedded devices. This layer should be used on top of Yocto's distribution, [Poky](http://git.yoctoproject.org/cgit/cgit.cgi/poky). You'll need to clone the poky repo, then clone meta-labview into the layer location for poky and add it as an additional layer. From there, you can run `bitbake core-image-minimal-chroot`, which will generate an image tarball. You can then use this image tarball with the [lvrt-deb-pkg](https://github.com/MakerHub/lvrt-deb-pkg) repo to create a package to be used on a debian-based OS installed on the board, else you can install the chroot manually. After this, you should be able to work with the board from LabVIEW but you will be unable to install any software to it from MAX. It should have most of the NI software you'd need.

**Comment by amstewart** [comment]
Closing historic and stale issues.
