### ISSUE TITLE
Legacy Bios

### ISSUE THREAD

**Issue by johnstonjay** [ni/nilrt#140]
How can i add Legacy Bios support i will do the legwork if needed i want to deploy on a computer for development that is non UEFI

**Comment by chaitu236** [comment]
Legacy BIOS support was present previously but was removed. So you can try creating "NI Linux RT Recovery USB Drive" from MAX (instructions [here](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA03q000000x4CsCAI&l=en-US)) on a windows host with [NI Linux RT System Image](https://www.ni.com/en-us/support/downloads/software-products/download.ni-linux-rt-system-image.html#329488) version 2019.09 or older installed (they had support for BIOS) and booting your hardware with it.

Can you tell us what non-UEFI hardware you are intending to run on? If the intention is to just get it working for development purposes, it is also possible to use a VM with UEFI support enabled - we have used QEMU, HyperV and VMWare Workstation without issues.

**Comment by johnstonjay** [comment]
I’m trying to develop on a older Phar Lap chassis and a shuttle pc how hard would it be to branch legacy bios support back in. 

In my development experience with other Linux OSs like Ubuntu it’s typically not to hard to shift grub back and forth from uefi and legacy. Need to modify the files and /boot and run the grub configuration command. This would be a life saver for me.

Or could I start with 2019 build then update the package to present?

**Comment by chaitu236** [comment]
[This](https://github.com/ni/meta-nilrt/commit/cd773672d3c66ced854bf81558a7858d36f17445) is the commit where the support was removed - and you can see that the disk is partitioned differently so it may not be possible to manually modify files, etc to get it working with BIOS. Unfortunately that particular iso is not buildable outside NI as it requires pieces that aren't present in our github repos. 

But I don't believe you would necessarily require latest version of safemode (which is what the NI Linux RT Recovery USB Drive installs). On a freshly provisioned target, a Base System Image is installed prior to installing any drivers/software. And the latest versions of Base System Image can (usually) still be installed on targets provisioned with older safemodes.

So my suggestion is to provision target with Recovery USB drive created from 2019.09 or older NI Linux RT System Image but use the latest version of NI Linux RT System Image to install software.

Note that we use some EFI variables so there may be issues with booting/running correctly. 

Can you tell us which Pharlap chassis/controller you're using?

**Comment by johnstonjay** [comment]
Sure it’s an older 8830 pXI.

**Comment by chaitu236** [comment]
Closing the issue for now. Feel free to reopen and let us know if you need any more info.

**Comment by johnstonjay** [comment]
Can you provide me the image I went to download it and it won’t let me.

**Comment by chaitu236** [comment]
NI Linux RT System Image 2019.09 can also be installed from NI Package Manager (Browse Products -> Search for System Image).

**Comment by johnstonjay** [comment]
I’m trying to do what you said with 2019.09 but it’s not working gets stuck here. Can you send me an image possibly help please.

**Comment by chaitu236** [comment]
> but it’s not working gets stuck here.

Can you clarify what gets stuck - does installing the system image on the windows host gets stuck or does provisioning the target gets stuck? Can you attach a screenshot?

**Comment by johnstonjay** [comment]
You did not get the screenshot? It gets stuck at 

Loading… BZ image …ok 
Loading… INITRD…ok

So I flashed the drive then plugged it into the computer then boot goes into bios booting screen then stars the USB then gets stuck at the above.
