### ISSUE TITLE
Build Error: master/hardknott

### ISSUE THREAD

**Issue by om327** [ni/nilrt#188]
Hi, 

I'm having issues building the latest version. I  managed to compile the repositories using the pyrex docker container using the guidance but hit the following error when i try to build an image..

```
ERROR: nilrt-safemode-initramfs-9.2-r0 do_rootfs: Unable to update the package index files. Command '/mnt/storage/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /mnt/storage/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/opkg.conf -t /mnt/storage/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/temp/ipktemp/ -o /mnt/storage/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/rootfs  --force_postinstall --prefer-arch-to-version  --add-exclude python-core --add-exclude python3-core --add-exclude rauc-mark-good update' returned 1:
 * opkg_validate_cached_file: Failed to download http://download.ni.com/ni-linux-rt/feeds/2023Q1/ni-main/Packages.gz headers: HTTP response code said error.
 * rm_r: Failed to open dir /mnt/storage/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/temp/ipktemp//opkg-g4lMHv: No such file or directory.
Downloading file:///mnt/storage/nilrt/build/tmp-glibc/deploy/ipk/all/Packages.gz.
Updated source 'NIOE-all'.
Downloading file:///mnt/storage/nilrt/build/tmp-glibc/deploy/ipk/x64/Packages.gz.
Updated source 'NIOE-x64'.
Downloading file:///mnt/storage/nilrt/build/tmp-glibc/deploy/ipk/core2-64/Packages.gz.
Updated source 'NIOE-core2-64'.
Downloading http://download.ni.com/ni-linux-rt/feeds/2023Q1/ni-main/Packages.gz.

ERROR: Logfile of failure stored in: /mnt/storage/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/temp/log.do_rootfs.588
ERROR: Task (/mnt/storage/nilrt/sources/meta-nilrt/recipes-core/images/nilrt-safemode-initramfs.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5687 tasks of which 5667 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /mnt/storage/nilrt/sources/meta-nilrt/recipes-core/images/nilrt-safemode-initramfs.bb:do_rootfs
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```
When I tried to download the links in the messages I hit a 404 error - has NI changed these feeds?

Many thanks, 
Ollie

**Comment by amstewart** [comment]
Hey Ollie,

The `ni-*` feeds (like `ni-main`) that OE uses to compose the image are proprietary software feeds that NI publishes independently of the NILRT. When building from outside of NI's corporate network, you'll need to inform bitbake of the latest public release that [you have access to](http://download.ni.com/#ni-linux-rt/feeds/). As of today, the latest is `2022Q3` [1].

So, per [this line in the README](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/README.md?plain=1#L60), you should add `NILRT_MAIN_FEED_VERSION = "2022Q3"` to your `/mnt/storage/nilrt/build/conf/local.conf` file.

This is a relatively new workflow that we've enabled, so please let me know if that doesn't work or if there is something we could do to make it easier.

[1] `2022Q4` will be published in the next couple weeks

**Comment by om327** [comment]
Hey - Thanks i'd missed that bit!

I tried again but ended up with several other errors so i did a complete reinstall of ubuntu 22.04 and changed the file location to ensure the current user has access. The docker container built sucessfully however after selecting ```echo 'NILRT_MAIN_FEED_VERSION ="2022Q3"' >> .conf/local.conf``` and then building the ```packagefeed-ni-core``` i get the following error:
```
ERROR: rauc-1.6-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export SSH_AUTH_SOCK="/tmp/pyrex/sock/svl-SSH_AUTH_SOCK"; export PATH="/home/svl/Documents/nilrt/sources/openembedded-core/scripts:/home/svl/Documents/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/rauc/1.6-r0/recipe-sysroot-native/usr/bin/x86_64-nilrt-linux:/home/svl/Documents/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/rauc/1.6-r0/recipe-sysroot/usr/bin/crossscripts:/home/svl/Documents/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/rauc/1.6-r0/recipe-sysroot-native/usr/sbin:/home/svl/Documents/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/rauc/1.6-r0/recipe-sysroot-native/usr/bin:/home/svl/Documents/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/rauc/1.6-r0/recipe-sysroot-native/sbin:/home/svl/Documents/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/rauc/1.6-r0/recipe-sysroot-native/bin:/home/svl/Documents/nilrt/sources/bitbake/bin:/home/svl/Documents/nilrt/build/tmp-glibc/hosttools"; export HOME="/home/svl"; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /home/svl/Documents/nilrt/build/downloads 'https://github.com/rauc/rauc/releases/download/v1.6/rauc-1.6.tar.xz' --progress=dot -v failed with exit code 8, no output
ERROR: rauc-1.6-r0 do_fetch: Fetcher failure for URL: 'https://github.com/rauc/rauc/releases/download/v1.6/rauc-1.6.tar.xz'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/svl/Documents/nilrt/build/tmp-glibc/work/core2-64-nilrt-linux/rauc/1.6-r0/temp/log.do_fetch.50893
ERROR: Task (/home/svl/Documents/nilrt/sources/meta-rauc/recipes-core/rauc/rauc_1.6.bb:do_fetch) failed with exit code '1'
WARNING: python3-avahi-0.6.32-r0 do_fetch: Failed to fetch URL https://github.com/lathiat/avahi/releases/download/v0.6.32/avahi-0.6.32.tar.gz, attempting MIRRORS if available
WARNING: protobuf-native-3.15.2-r0 do_fetch: Failed to fetch URL git://github.com/protocolbuffers/protobuf.git;branch=master;protocol=https, attempting MIRRORS if available
NOTE: Tasks Summary: Attempted 1338 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/svl/Documents/nilrt/sources/meta-rauc/recipes-core/rauc/rauc_1.6.bb:do_fetch
Summary: There were 9 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
```
Is there something else i'm missing?

**Comment by om327** [comment]
Rebuilding the ```ni-core``` and ```ni-extra``` packages gets me a little further but now the build fails when i try building an image. 

I've built the ```package-index``` but in previous versions there was a python localhost server to act as a repository and package feed, that doesn't appear to be available anymore in the ```tmp-glibc/deploy/ipk/...``` folders?

When attempting to build ```nilrt-safemode-rootfs``` gives the following error:

```
Initialising tasks: 100% |###############################################################| Time: 0:00:13
Sstate summary: Wanted 234 Local 230 Network 0 Missed 4 Current 1459 (98% match, 99% complete)
NOTE: Executing Tasks
ERROR: nilrt-safemode-initramfs-9.2-r0 do_rootfs: Unable to install packages. Command '/home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/opkg.conf -t /home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/temp/ipktemp/ -o /home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/rootfs  --force_postinstall --prefer-arch-to-version  --add-exclude python-core --add-exclude python3-core --add-exclude rauc-mark-good --add-exclude python-core --add-exclude python3-core --add-exclude rauc-mark-good --add-ignore-recommends shared-mime-info --add-ignore-recommends xf86-input-libinput install libnitargetcfg ni-auth ni-auth-webservice ni-avahi-client ni-ca-certs ni-rt-exec-webservice ni-sdmon ni-service-locator ni-skyline-file-client ni-skyline-message-client ni-skyline-tag-client ni-software-action-services ni-software-installation-daemon ni-software-installation-websvc ni-ssl-webserver-support ni-sysapi ni-sysapi-remote ni-sysapi-webservice ni-sysmgmt-auth-utils ni-system-webserver ni-traceengine ni-webdav-system-webserver-support ni-webserver-libs ni-webservices-webserver-support ni-wif-landingpage ni-wifibledd ni-wireless-ath6kl ni-wireless-cert-management-webservice ni-wireless-cert-storage nicurl nirtcfg nirtmdnsd nissl' returned 255:
 * opkg_prepare_url_for_install: Couldn't find anything to satisfy 'ni-rt-exec-webservice'.

ERROR: Logfile of failure stored in: /home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/temp/log.do_rootfs.587
ERROR: Task (/home/svl/Documents/nilrt/sources/meta-nilrt/recipes-core/images/nilrt-safemode-initramfs.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5687 tasks of which 5668 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/svl/Documents/nilrt/sources/meta-nilrt/recipes-core/images/nilrt-safemode-initramfs.bb:do_rootfs
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

```

**Comment by amstewart** [comment]
> Rebuilding the `ni-core` and `ni-extra` packages gets me a little further but now the build fails when i try building an image.

The scripts in the `:scripts/pipelines/` directory might help here - specifically [`build.core-feeds.sh`](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/scripts/pipelines/build.core-feeds.sh). They're the scripts that we use internally to build the package feeds; though it sounds like you're doing the right thing.

If you want to build through to images, then you only have to build the core feed. The extras feed is only for extraneous packages that you might want during runtime.

> I've built the `package-index` but in previous versions there was a python localhost server to act as a repository and package feed, that doesn't appear to be available anymore in the `tmp-glibc/deploy/ipk/...` folders?

I'm not sure what python server you're thinking of. Bitbake should still deposit the feeds and index files in the directory that you referenced. And we've never intentionally distributed a python server to host those feeds, (it isn't needed for bitbake to use them), but you can trivially host one with `python3 -m http.server $port`.

> When attempting to build `nilrt-safemode-rootfs` gives the following error:
> 
> ```
> Initialising tasks: 100% |###############################################################| Time: 0:00:13
> Sstate summary: Wanted 234 Local 230 Network 0 Missed 4 Current 1459 (98% match, 99% complete)
> NOTE: Executing Tasks
> ERROR: nilrt-safemode-initramfs-9.2-r0 do_rootfs: Unable to install packages. Command '/home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/opkg.conf -t /home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/temp/ipktemp/ -o /home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/rootfs  --force_postinstall --prefer-arch-to-version  --add-exclude python-core --add-exclude python3-core --add-exclude rauc-mark-good --add-exclude python-core --add-exclude python3-core --add-exclude rauc-mark-good --add-ignore-recommends shared-mime-info --add-ignore-recommends xf86-input-libinput install libnitargetcfg ni-auth ni-auth-webservice ni-avahi-client ni-ca-certs ni-rt-exec-webservice ni-sdmon ni-service-locator ni-skyline-file-client ni-skyline-message-client ni-skyline-tag-client ni-software-action-services ni-software-installation-daemon ni-software-installation-websvc ni-ssl-webserver-support ni-sysapi ni-sysapi-remote ni-sysapi-webservice ni-sysmgmt-auth-utils ni-system-webserver ni-traceengine ni-webdav-system-webserver-support ni-webserver-libs ni-webservices-webserver-support ni-wif-landingpage ni-wifibledd ni-wireless-ath6kl ni-wireless-cert-management-webservice ni-wireless-cert-storage nicurl nirtcfg nirtmdnsd nissl' returned 255:
>  * opkg_prepare_url_for_install: Couldn't find anything to satisfy 'ni-rt-exec-webservice'.
> 
> ERROR: Logfile of failure stored in: /home/svl/Documents/nilrt/build/tmp-glibc/work/x64-nilrt-linux/nilrt-safemode-initramfs/9.2-r0/temp/log.do_rootfs.587
> ERROR: Task (/home/svl/Documents/nilrt/sources/meta-nilrt/recipes-core/images/nilrt-safemode-initramfs.bb:do_rootfs) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 5687 tasks of which 5668 didn't need to be rerun and 1 failed.
> 
> Summary: 1 task failed:
>   /home/svl/Documents/nilrt/sources/meta-nilrt/recipes-core/images/nilrt-safemode-initramfs.bb:do_rootfs
> Summary: There was 1 ERROR message shown, returning a non-zero exit code.
> ```

Ah. The `ni-rt-exec-webservice` is one of the proprietary packages that the image do_rootfs pulls from the "NILRT_MAIN_FEED" on download.ni.com. For the 22Q3 release, someone messed up and didn't publish that specific IPK with the others. We didn't notice until after release and, since building the image targets wasn't a supported workflow at the time, didn't fix it retroactively.

Try replacing the `NILRT_MAIN_FEED_VERSION = "2022Q3"` in your local.conf with "2022Q4" and then rerunning the image targets. We *just* published those feeds, and they should have all the IPKs in-place.

**Comment by om327** [comment]
Thanks, Alex, 

Its been awhile since i last tried to build an image (20.7/sumo) which had the option to set up a local feed using python:

_(Optional/Advanced) Bitbake can transform tmp-glibc/deploy/ipk/ into a package feed when you run the following command:_

```bitbake package-index```

Your build machine can then host the feed by running the following command:

 ```cd tmp-glibc/deploy/ipk/ && python -m SimpleHTTPServer 8080```

I'll have a go at rebuilding the image using 2022Q4 and let you know how I get on - is there already a QEMU bootable image?

I'm still hoping to recompile to ARM but first things first I'll try and build the latest version. 

Thanks again!

**Comment by amstewart** [comment]
> _(Optional/Advanced) Bitbake can transform tmp-glibc/deploy/ipk/ into a package feed when you run the following command:_

Oh; yeah. That's basically the same advice as above, just using the python2 `http` module instead of python3.

> I'll have a go at rebuilding the image using 2022Q4 and let you know how I get on - is there already a QEMU bootable image?

I don't think we have a publically-distributed QEMU VM anywhere. But once you have the MAIN feed switched to 2022Q4 and can build the safemode images, you just need to [`bitbake nilrt-recovery-media`](https://github.com/ni/meta-nilrt/blob/nilrt/master/hardknott/recipes-core/images/nilrt-recovery-media.bb) - which will generate a `:tmp-glibc/deploy/images/x64/nilrt-recovery-media-x64.iso`. Then run the [`../scripts/pipelines/build.vms.sh`](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/scripts/pipelines/build.vms.sh) script from your bitbake environment - and it should automagically provision a QEMU VM for you.

> I'm still hoping to recompile to ARM but first things first I'll try and build the latest version.

Hmm; that gets complicated. What are you ultimately working toward?

**Comment by om327** [comment]
> Hmm; that gets complicated. What are you ultimately working toward?

We have embedded devices we would like to provision with VIs. The embedded devices are expendable due to the nature of what we're using them for. Unfortunately, the cRIO and MyRio aren't options due to cost and LINX for other boards doesn't give us the functionality we're after. We're hoping with an ARM nilrt RTOS we can then provision with VIs through MAX or SystemLink as if it were a cRIO.

**Comment by amstewart** [comment]
Yeah; that's where it gets complicated. ARM32 content is only supported in the sumo mainline `nilrt/master/sumo`, but that doesn't include the new generation of tooling you need to build full images. Basically everything in this thread doesn't exist, and it requires content which we install via private components (ie. not on GH). You *might* be able to get an NILRT build working with only the open-source packages, but you'll be missing some key components which make MAX connectivity and LV RT deployment work.

The hardknott mainline can build feeds and images, but has divested from ARM32 support.

And neither mainline has tried to support ARM64 yet.

**Comment by amstewart** [comment]
There hasn't been any activity on this thread for a couple weeks, so I'm going to close the issue. Let me know if you disagree. Or we can open a new issue if there is some specific issue with the mainline's feed configuration.
