### ISSUE TITLE
Question: When you you use NI-Realtime Linux with Labview extended period of time consuming all the available ram and becoming unresponsive 

### ISSUE THREAD

**Issue by johnstonjay** [ni/nilrt#200]
When you use NI-Realtime Linux with Labview install vs python does the system leverage Wine in some capacity i notice the file hierarchy leverages /c/NI and there are .ini files there if so do you see issues with memory leaks? I am seeing some chassis that are left on for an extended period of time consuming all the available ram and becoming unresponsive. I can post some screenshots if needed i would really appreciate the info.  
![MicrosoftTeams-image](https://user-images.githubusercontent.com/63012311/205176471-849efde7-1c4a-4972-92f1-be4d3ec1e73d.png)

**Comment by johnstonjay** [comment]
Note this is only when Leveraging the LabView Suite of apps like Verastand with the Chassis when using the Python env this does not happen. Why i want to know if wine or other windows emulation software is used.

**Comment by amstewart** [comment]
Hey Jay. The LabVIEW runtime isn't running in a wine prefix; it's a native C implementation. Likewise for the rest of the LV suite, AFAIK.

The `/c/` and `/C/` paths you see are owned by the LV packages, and are there for backwards compatibility with legacy LV applications built for the old Pharlap RTOS. The INI files are native linux as well. Though it's true that NI's affinity for INI is a function of developers being comfortable with Windows development, they don't imply a wine prefix.

The NI support channels are probably your best bet to get help debugging the memory leak. The support engineers are the LV experts and are experienced with debugging those kinds of issues. Plus, they're in a position where you can share your project with them, if need-be.

**Comment by johnstonjay** [comment]
Thank you very much
