### ISSUE TITLE
KERNEL_SOURCE.txt does not mention required host build tools

### ISSUE THREAD

**Issue by negentropicdev** [ni/nilrt#203]
Perhaps an oversight of developers installing linux with development tools pre-selected but the kernel_source.txt calls out requiring Make but not host GCC and other dependencies. Another required package on some systems was openssl-devel

**Comment by amstewart** [comment]
ACK; good catch. I'll also note that we moved the KERNEL_SOURCE.txt document into [README.kernel.md](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/docs/README.kernel.md) in the new mainlines. But the requirements expressed in that doc are the same and exhibit this issue.

**Comment by amstewart** [comment]
I believe this issue should be fixed in the sumo mainline by #204. I've cherry-picked the relevant changes to the hardknott and kirkstone mainlines as well.
