### ISSUE TITLE
Failed to fetch URL git://code.qt.io/qt/qtbase.git;name=qtbase;branch=5.15.2;protocol=git

### ISSUE THREAD

**Issue by mruizglz** [ni/nilrt#206]
Executing bitbake packagefeed-ni-core I am getting this error, "Failed to fetch URL git://code.qt.io/qt/qtbase.git;name=qtbase;branch=5.15.2;protocol=git"
I am using an Ubuntu 22.04 .
Is there any workaround to solve the issue?

**Comment by mruizglz** [comment]
Issue solved adding nobranch=1 in qt5-git.inc

```
# each module needs to define valid SRCREV
SRC_URI = " \
    ${QT_GIT}/${QT_MODULE}.git;name=${QT_MODULE};${QT_MODULE_BRANCH_PARAM};protocol=${QT_GIT_PROTOCOL};nobranch=1 \
"
```

**Comment by JKSH** [comment]
Looks like someone made a mistake upstream. The correct value of `QT_MODULE_BRANCH` should be "5.15", not "5.15.2". 

This was fixed in March 2022: https://github.com/meta-qt5/meta-qt5/blob/master/recipes-qt/qt5/qt5-git.inc

**Comment by shruthi-ravi** [comment]
@mruizglz, @JKSH thank you for bringing this to our attention. We'll fix the branch value shortly.

**Comment by chaitu236** [comment]
@mruizglz, @JKSH This should be fixed now. Closing the issue.
