### ISSUE TITLE
NI RT Linux LabView Can instability

### ISSUE THREAD

**Issue by johnstonjay** [ni/nilrt#235]
I have a question about the NI-RTLinux Labview X-Net Dongles and the software interface. I have been seeing this issue with socket can protocol with 10ms signals that have checksum dropping out I wanted to know if you have seen this or if you are using socket can? If so can we change the connection interface to an internal transport that we host within the company?

**Comment by amstewart** [comment]
Hey Jay. This repo (and the other NI LinuxRT GH repos) are monitored by the LinuxRT distribution and kernel maintainers. While we're experts on the open-source software that goes into the distribution, we don't have as much expertise in LabVIEW or XNET. So we probably can't help you very much here.

The [NI Community Forums](https://forums.ni.com/t5/Discussion-Forums/ct-p/discussion-forums) are frequented by community experts, who may be able to give you some advice. And you can [start a conversation](https://www.ni.com/en-us/support.html#requestsupport) with NI's Support Engineers, who can provide you direct help with your application.

Hope that helps!

**Comment by johnstonjay** [comment]
Please That would be great

**Comment by amstewart** [comment]
What would be great?

**Comment by johnstonjay** [comment]
Sorry i meant getting contact I made a ticket yesterday. I want to get this bug fixed. The bug is with the socket can transport not unique to NI it's any can hardware using the socket can transport. Why I wanted to verify that transport. I also will report the issue on the socket can GitHub repo after I find it. Feel free to close I appreciate the help.
