### ISSUE TITLE
The firmware version is incorrect after compilation

### ISSUE THREAD

**Issue by tonycc521** [ni/nilrt#260]
I compiled ni linux rt according to the readme document, after compiling successfully, I could install the system, but when MAX installed the software, the firmware version was incorrect
![Uploading ERROR.png…]()

**Comment by amstewart** [comment]
Hey Tony. It looks like your attached image hasn't uploaded correctly. Could you fix that or otherwise provide some more info about what branch you built and what firmware is being reported in MAX?

**Comment by tonycc521** [comment]
![Uploading ERROR.png…]()

**Comment by tonycc521** [comment]
![Uploading ERROR.png…]()

**Comment by tonycc521** [comment]
![Uploading ERROR.png…]()

**Comment by tonycc521** [comment]
Sorry, I don't know why I can't upload pictures，MAX is displayed when the disk is formatted：”Current version: dev-nilrt Reauired version: 7.0“

**Comment by amstewart** [comment]
Ah. So I assume you've built your own safemode image and are trying to use it as the firmware image in MAX's reformat operation. I think MAX is trying to check the that the OS-version is recent enough that it is supported in your version of MAX. The `dev-nilrt` string is coming from the `BUILDNAME` variable in OpenEmbedded, which we have weakly set to that development string by default.

Go into your OE environment's `build/conf/local.conf` file and set the value of `BUILDNAME` to whatever NILRT version you're trying to emulate. (If you tell me what branch you're trying to build, I can confirm the value you need.) Then rebuild the safemode image and try the format operation again.

**Comment by tonycc521** [comment]
https://github.com/ni/nilrt/blob/nilrt/23.5/hardknott/

**Comment by amstewart** [comment]
Try `BUILDNAME = "9.4"`.

**Comment by tonycc521** [comment]
thankyou
