### ISSUE TITLE
Cannot modify resolution

### ISSUE THREAD

**Issue by tonycc521** [ni/nilrt#265]
I installed NI LinuxRT on the PC, but the resolution only a default 800*600, this is not right, there is no way to change the resolution?
![1234](https://github.com/ni/nilrt/assets/47617106/d4d65bc6-1b17-45cb-8090-ec9df1f8e508)

**Comment by tonycc521** [comment]
I use an Intel N97 CPU

**Comment by amstewart** [comment]
Hey Tony. Can you give some more details about your hardware setup here. Are you running NILRT on a VM, or is this real hardware?

**Comment by tonycc521** [comment]
This is a real hardware，Look at the picture below
![www](https://github.com/ni/nilrt/assets/47617106/0496f49b-df60-442f-bb5f-c11d1e333ded)

**Comment by amstewart** [comment]
I assume you're using something like a UP7000. I can't really help to support that platform, or anything which isn't NI hardware. But looking at the datasheet: I don't see any reason that NILRT x64 shouldn't work as configured. The issue suggests to me that the `i915` driver isn't being loaded for some reason. So I would recommend looking through the `dmesg` log for errors related to that driver or the graphical stack more generally.

Good luck.
