### ISSUE TITLE
Y2038 ARM

### ISSUE THREAD

**Issue by ngladitz** [ni/nilrt#272]
Hi! Not entirely sure this is the right place to bring this up.

I've got a sbRIO 9651 (32-bit ARM) that appears to be affected by the [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem).

From what I understand Linux >= 5.1 and glibc >= 2.34 (better yet 2.35) would provide opt-in mitigations in form of a 64-bit `time_t`.

I've updated my system software installation to the currently most recent 2024Q1 (for which I've been unable to find corresponding tags / branches in this repository btw.) and find the presumably too old Linux 4.14.146-rt67 and glibc 2.24.

I also notice that the `nilrt/master/sumo` branch hasn't been touched in two years and the note in `docs/README.kernel.md` about only supporting Linux 4.14 and below on ARM.

Is the issue known / being worked on?
Is the ARM port still being worked on at all or has it perhaps moved elsewhere (I assume the updated system image releases have to be coming from somewhere)?

**Comment by jeminor** [comment]
Hi @ngladitz and thanks for asking!

> Not entirely sure this is the right place to bring this up.

This is a fine place to start, but from here I think your best option is to reach out to your local NI/Emerson sales and support team and have them raise a support issue.  We would like to understand more about your use case, needs and timelines and that is typically the best pathway for us to gather that information comprehensively.

I will close this issue in favor of that communication pathway.
