### ISSUE TITLE
Failed to download http://download.ni.com/ni-linux-rt/feeds/2022Q3/ni-main/Packages.gz headers: Couldn't resolve host name

### ISSUE THREAD

**Issue by Nettoysfkf** [ni/nilrt#275]
my build machine: x86-64
build branch: nilrt/master/kirkstone
build target:  nilrt-base-system-image
my error: 
```
ERROR: nilrt-runmode-rootfs-1.0-r0 do_rootfs: Unable to update the package index files. Command '/media/ucas/yocto/ni/nilrt/build-x86-64/tmp-glibc/work/x64-nilrt-linux/nilrt-runmode-rootfs/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /media/ucas/yocto/ni/nilrt/build-x86-64/tmp-glibc/work/x64-nilrt-linux/nilrt-runmode-rootfs/1.0-r0/opkg.conf -t /media/ucas/yocto/ni/nilrt/build-x86-64/tmp-glibc/work/x64-nilrt-linux/nilrt-runmode-rootfs/1.0-r0/temp/ipktemp/ -o /media/ucas/yocto/ni/nilrt/build-x86-64/tmp-glibc/work/x64-nilrt-linux/nilrt-runmode-rootfs/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version  --add-exclude rauc --add-exclude rauc-mark-good update' returned 1:
 * opkg_validate_cached_file: Failed to download http://download.ni.com/ni-linux-rt/feeds/2022Q3/ni-main/Packages.gz headers: Couldn't resolve host name.
Downloading file:///media/ucas/yocto/ni/nilrt/build-x86-64/tmp-glibc/deploy/ipk/all/Packages.gz.
Updated source 'NIOE-all'.
Downloading file:///media/ucas/yocto/ni/nilrt/build-x86-64/tmp-glibc/deploy/ipk/x64/Packages.gz.
Updated source 'NIOE-x64'.
Downloading file:///media/ucas/yocto/ni/nilrt/build-x86-64/tmp-glibc/deploy/ipk/core2-64/Packages.gz.
Updated source 'NIOE-core2-64'.
Downloading http://download.ni.com/ni-linux-rt/feeds/2022Q3/ni-main/Packages.gz.
```
I run ping download.ni.com fine in my host
```
PING download.ni.com (60.9.4.70) 56(84) bytes of data.
64 bytes from 60.9.4.70: icmp_seq=1 ttl=49 time=20.8 ms
64 bytes from 60.9.4.70: icmp_seq=2 ttl=49 time=23.5 ms
64 bytes from 60.9.4.70: icmp_seq=3 ttl=49 time=23.0 ms
```
I run wget fine in my host
```
--2024-06-07 06:39:52--  http://download.ni.com/ni-linux-rt/feeds/2022Q3/ni-main/Packages.gz
Resolving download.ni.com (download.ni.com)... 60.9.4.70, 2408:871a:8810:205:3d4b:e240:6811:fffe
Connecting to download.ni.com (download.ni.com)|60.9.4.70|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 74375 (73K) [application/x-gzip]
Saving to: ‘Packages.gz’

Packages.gz                           100%[========================================================================>]  72.63K   177KB/s    in 0.4s

2024-06-07 06:39:55 (177 KB/s) - ‘Packages.gz’ saved [74375/74375]
```
why opkg update failed?

**Comment by Nettoysfkf** [comment]
I tried many many times.

**Comment by amstewart** [comment]
Hey. Assuming you're using the normal build workflow, your bitbake actions are run within the pyrex docker container. It's possible that DNS resolution within the container environment is messed up.

After sourcing the `ni-oe-init-build-env` script, try running
```bash
pyrex-run wget 'http://download.ni.com/ni-linux-rt/feeds/2022Q3/ni-main/Packages.gz'
```

or your `ping` command again.

The `pyrex-run` wrapper script will pass your command into the docker execution environment. If it fails in that context, then there is something off with your docker configuration. I can't help too much with that, since it is specific to your build machine. 

But you might have to add this to your host machine's `/etc/docker/daemon.json` file.
```json
{
    "dns": ["8.8.8.8"]
}
```

**Comment by DengkeDu** [comment]
> Hey. Assuming you're using the normal build workflow, your bitbake actions are run within the pyrex docker container. It's possible that DNS resolution within the container environment is messed up.
> 
> After sourcing the `ni-oe-init-build-env` script, try running
> 
> ```shell
> pyrex-run wget 'http://download.ni.com/ni-linux-rt/feeds/2022Q3/ni-main/Packages.gz'
> ```
This is ok for me
> 
> or your `ping` command again.
and this
> 
> The `pyrex-run` wrapper script will pass your command into the docker execution environment. If it fails in that context, then there is something off with your docker configuration. I can't help too much with that, since it is specific to your build machine.
> 
> But you might have to add this to your host machine's `/etc/docker/daemon.json` file.
> 
> ```json
> {
>     "dns": ["8.8.8.8"]
> }
> ```
still failed update, maybe something with my docker environment

**Comment by Nettoysfkf** [comment]
> Hey. Assuming you're using the normal build workflow, your bitbake actions are run within the pyrex docker container. It's possible that DNS resolution within the container environment is messed up.
> 
> After sourcing the `ni-oe-init-build-env` script, try running
> 
> ```shell
> pyrex-run wget 'http://download.ni.com/ni-linux-rt/feeds/2022Q3/ni-main/Packages.gz'
> ```
This is ok for me
> 
> or your `ping` command again.

and this

> 
> The `pyrex-run` wrapper script will pass your command into the docker execution environment. If it fails in that context, then there is something off with your docker configuration. I can't help too much with that, since it is specific to your build machine.
> 
> But you might have to add this to your host machine's `/etc/docker/daemon.json` file.
> 
> ```json
> {
>     "dns": ["8.8.8.8"]
> }
> ```
still failed update, maybe something with my docker environment

**Comment by JamesWiresmith** [comment]
@Nettoysfkf did you find a solution? I'm hitting the same issues. wget seems fine when run directly but I keep getting the same failur in bitbake
