### ISSUE TITLE
Trying to Build recovery image for cRIO-9045

### ISSUE THREAD

**Issue by resnikal71202** [ni/nilrt#32]
Hello there,
I am very inexperienced with this.
Nevertheless, I need a recoervery image for a cRIO with x86_64 architecture(cRIO-9045). The following steps I have done, but without success:
install all packages from the list Yocto Project Quick Start guide+python
```
 git clone https://github.com/ni/nilrt.git
 cd nilrt
 git checkout nilrt/20.0/sumo
 git submodules init
 git submodule update --remote --checkout
 . ni-oe-init-build-env
 export MACHINE=x64
 export DISTRO=nilrt
 bitbake packagegroup-ni-coreimagerepo
```
Here my system gives me the following debug info:
[shell_output.txt](https://github.com/ni/nilrt/files/5622466/shell_output.txt)
the log from glib-2.0-native:
[log.do_compile.1138304.txt](https://github.com/ni/nilrt/files/5622512/log.do_compile.1138304.txt)
could you help me with this?
kind regards

**Comment by corneydavid** [comment]
Hi resnikal71202,

First, there is confusion as to what you are trying to achieve by rebuilding the kernel. If you are wanting to create a recovery image for a cRIO, there are tools in NI-MAX that will allow you to do this.

Second, this is probably not the best place to post these types of questions. The GitHub repository is intended for developers working on the code within the kernel. Can I suggest you post your question on the NI forum, specifically for the NI LInux RT OS at: https://forums.ni.com/t5/NI-Linux-Real-Time-Discussions/bd-p/7111?profile.language=en. There you will find people who can offer help and advice. Thanks.

**Comment by resnikal71202** [comment]
What i was trying to achive was building restore-mode-image (step 5 readme). Therefor i had to build everything in packagegroup-ni-coreimagerepo (step 3) and build a feed (optional step 4) to build images (readme). Then flash it to a usbstick and boot of it.

**Comment by jeminor** [comment]
Hi @resnikal71202 : Small clarification of what @corneydavid said above.  For your issue specifically, if you are trying to get a recovery key for use on a broken NI target, then the forums David listed above is the right place to go to get one that is already pre-made (you don't have to build it from scratch).  If your target needs a recovery image, we'd like to hear more about how it got into that state on the NI forums linked above.

This repo is also absolutely available for those attempting to build and use any of the NI maintained Open Source components both inside and outside of NI.  Questions here are always welcome, and let us know if you need any further assistance!
