### ISSUE TITLE
Building SDK for 2020 release seems to be broken

### ISSUE THREAD

**Issue by edbordin** [ni/nilrt#40]
I'd be happy to use a pre-built 2020 SDK instead but I couldn't find one released anywhere.

Building `nativesdk-glibc` results in the following error due to `-Werror`:
```
| In file included from ../sysdeps/unix/sysv/linux/sigwait.c:24:0:
| ../nptl/pthreadP.h:604:1: error: 'prio_inherit_missing' defined but not used [-Werror=unused-function]
|  prio_inherit_missing (void)
```

Unsure if removing the error on `unused-function` is a valid solution or if this is a symptom of something not configuring correctly.

I've tried building from `RELEASE_NILRT_2020.1` and `nilrt/20.5/sumo` with the same result. I also tried in both Ubuntu 18.04 and inside the provided Docker environment with the same result.

I'm just running these commands to build the linux host SDK:

```
. ni-oe-init-build-env
export MACHINE=x64
SDKMACHINE=x86_64 bitbake -c populate_sdk host-toolchain-sysroot
```

More detailed log here:
[error.txt](https://github.com/ni/nilrt/files/6065075/error.txt)

edit: If I add `__attribute__ ((unused))` to `prio_inherit_missing` then it at least builds `nativesdk-glibc` but there seem to be a bunch of other issues after that. Curious how this happened on a release tag - maybe because the system image was built for release but not the SDK?

edit 2: After chipping away at this on and off, I've found these patches on the submodules seem to be enough to get a usable cross toolchain when building inside the docker container, unsure if messing with the locale generation will break certain things though:

`nilrt/sources/meta-nilrt`:

```
diff --git a/recipes-core/glibc/glibc/0001-pi-condvars-add-protocol-support-to-pthread_condattr.patch b/recipes-core/glibc/glibc/0001-pi-condvars-add-protocol-support-to-pthread_condattr.patch
old mode 100644
new mode 100755
index b1195788..97d83d59
--- a/recipes-core/glibc/glibc/0001-pi-condvars-add-protocol-support-to-pthread_condattr.patch
+++ b/recipes-core/glibc/glibc/0001-pi-condvars-add-protocol-support-to-pthread_condattr.patch
@@ -187,7 +187,7 @@ index 4edc74b1ef..4cf5e50524 100644
  # define USE_REQUEUE_PI(mut) 0
  #endif

-+static bool
++static bool __attribute__ ((unused))
 +prio_inherit_missing (void)
 +{
 +#ifdef __NR_futex
```
 
`nilrt/sources/meta-mono`:

```
diff --git a/recipes-mono/mono/mono-git.inc b/recipes-mono/mono/mono-git.inc
old mode 100644
new mode 100755
index 290a969..31a8933
--- a/recipes-mono/mono/mono-git.inc
+++ b/recipes-mono/mono/mono-git.inc
@@ -7,7 +7,7 @@ LICENSE = "GPLv2"

 LIC_FILES_CHKSUM = "file://COPYING.LIB;md5=80862f3fd0e11a5fa0318070c54461ce"

-SRCBRANCH = "master"
+SRCBRANCH = "main"
 SRCREV = "${AUTOREV}"

 SRC_URI = "git://github.com/mono/mono.git;branch=${SRCBRANCH}\
```

`nilrt/sources/openembedded-core`:

```
diff --git a/meta/lib/oe/sdk.py b/meta/lib/oe/sdk.py
old mode 100644
new mode 100755
index d6a503372a..d158fb33bf
--- a/meta/lib/oe/sdk.py
+++ b/meta/lib/oe/sdk.py
@@ -42,7 +42,7 @@ def generate_locale_archive(d, rootfs):
     env = dict(os.environ)
     env["LOCALEARCHIVE"] = oe.path.join(localedir, "locale-archive")

-    for name in os.listdir(localedir):
+    for name in []:# os.listdir(localedir):
         path = os.path.join(localedir, name)
         if os.path.isdir(path):
             try:
@@ -147,7 +147,7 @@ class Sdk(object, metaclass=ABCMeta):
             generate_locale_archive(self.d, oe.path.join(self.sdk_host_sysroot, self.sdk_native_path))
             # And now delete the binary locales
             pkgs = fnmatch.filter(pm.list_installed(), "nativesdk-glibc-binary-localedata-*.utf-8")
-            pm.remove(pkgs)
+            #pm.remove(pkgs)
         else:
             # No linguas so do nothing
             pass
diff --git a/meta/recipes-core/glibc/glibc-locale.inc b/meta/recipes-core/glibc/glibc-locale.inc
old mode 100644
new mode 100755
index 0d80869650..5a14c35b14
--- a/meta/recipes-core/glibc/glibc-locale.inc
+++ b/meta/recipes-core/glibc/glibc-locale.inc
@@ -23,7 +23,7 @@ RDEPENDS_localedef += "glibc"

 # default to disabled
 ENABLE_BINARY_LOCALE_GENERATION = "0"
-ENABLE_BINARY_LOCALE_GENERATION_pn-nativesdk-glibc-locale = "1"
+ENABLE_BINARY_LOCALE_GENERATION_pn-nativesdk-glibc-locale = "0"

 #enable locale generation on these arches
 # BINARY_LOCALE_ARCHES is a space separated list of regular expressions
@@ -31,7 +31,7 @@ BINARY_LOCALE_ARCHES ?= "arm.* aarch64 i[3-6]86 x86_64 powerpc mips mips64"

 # set "1" to use cross-localedef for locale generation
 # set "0" for qemu emulation of native localedef for locale generation
-LOCALE_GENERATION_WITH_CROSS-LOCALEDEF = "0"
+LOCALE_GENERATION_WITH_CROSS-LOCALEDEF = "1"

 PROVIDES = "virtual/libc-locale"
```

edit 3: also needed this patch on `nilrt/sources/meta-openembedded`
```
diff -uraBN nilrt/sources/meta-openembedded/meta-python/recipes-devtools/python/python-dateutil/0001-setup.py-Pin-setuptools_scm.patch nilrt/sources/meta-openembedded/meta-python/recipes-devtools/python/python-dateutil/0001-setup.py-Pin-setuptools_scm.patch
--- nilrt/sources/meta-openembedded/meta-python/recipes-devtools/python/python3-dateutil/0001-setup.py-Pin-setuptools_scm.patch	1970-01-01 10:00:00.000000000 +1000
+++ nilrt/sources/meta-openembedded/meta-python/recipes-devtools/python/python3-dateutil/0001-setup.py-Pin-setuptools_scm.patch	2021-03-30 16:21:23.350000000 +1100
@@ -0,0 +1,25 @@
+From f230331f1c1766ea0e562a5573b0a5ad59fcc689 Mon Sep 17 00:00:00 2001
+From: Ed Bordin <ed@removed.com>
+Date: Tue, 30 Mar 2021 16:12:37 +1100
+Subject: [PATCH] pin setuptools_scm at version that works in python 3.5
+
+---
+ setup.py | 2 +-
+ 1 file changed, 1 insertion(+), 1 deletion(-)
+
+diff --git a/setup.py b/setup.py
+index b59bd63..c5afd94 100644
+--- a/setup.py
++++ b/setup.py
+@@ -63,7 +63,7 @@ setup(name="python-dateutil",
+       package_data={"dateutil.zoneinfo": ["dateutil-zoneinfo.tar.gz"]},
+       zip_safe=True,
+       requires=["six"],
+-      setup_requires=['setuptools_scm'],
++      setup_requires=['setuptools_scm==1.15.7'],
+       install_requires=["six >=1.5"],  # XXX fix when packaging is sane again
+       classifiers=[
+           'Development Status :: 5 - Production/Stable',
+-- 
+2.25.1
+
diff -uraBN nilrt/sources/meta-openembedded/meta-python/recipes-devtools/python/python-dateutil.inc nilrt/sources/meta-openembedded/meta-python/recipes-devtools/python/python-dateutil.inc
--- nilrt/sources/meta-openembedded/meta-python/recipes-devtools/python/python-dateutil.inc	2021-03-30 16:14:54.000000000 +1100
+++ nilrt/sources/meta-openembedded/meta-python/recipes-devtools/python/python-dateutil.inc	2021-03-30 16:18:29.590000000 +1100
@@ -4,6 +4,7 @@
 LICENSE = "BSD-3-Clause & Apache-2.0"
 LIC_FILES_CHKSUM = "file://LICENSE;md5=e3155c7bdc71f66e02678411d2abf996"
 
+SRC_URI_append_class-target = " file://0001-setup.py-Pin-setuptools_scm.patch "
 SRC_URI[md5sum] = "03a08c8bcf0a2b29f1cd21b9de4d12fb"
 SRC_URI[sha256sum] = "9d8074be4c993fbe4947878ce593052f71dac82932a677d49194d8ce9778002e"
```

**Comment by edbordin** [comment]
Also, any chance of upgrading glibc? Sumo ships with 2.27 upstream, you seem to have pinned it at 2.24. I'm unable to run the latest Intel OpenVINO release because of this :/

**Comment by gratian** [comment]
My colleagues are looking into your first question but I can answer your second question on why glibc is pinned to 2.24. It basically comes down to this glibc bug: https://sourceware.org/bugzilla/show_bug.cgi?id=11588. The short summary is glibc versions up to 2.24 require a series of patches to fix priority inversions in the conditional variable implementation. We applied these patches to the glibc versions in NI Linux RT and at various times we tried to help upstream these patches.

However, in glibc 2.25 upstream maintainers re-implemented the pthread conditional variables in response to a (still open) POSIX defect[1]. The new implementation was committed upstream and as the last comment in the bug linked above states _"there is no known solution for how to achieve PI support given the current constraints"_.  This breaks real-time guarantees in LabVIEW RT which relies on conditional variables to implement higher level primitives.

In response we started working on a replacement implementation for conditional variables (and mutexes) with priority inheritance support: librtpi [2][3]. If you want more of the gory details I did a presentation on it at ELC 2020 [4[5].

Since with librtpi we do have a way forward we are planning to unpin the glibc version and you can see that in our (currently Dunfell) development branch[6]. The switchover is complicated by having to maintain backwards compatibility so it's taking us a bit longer than we would like.

If your application doesn't have strict real-time constraints (or if you are already on LabVIEW RT 2020 which has been patched to use librtpi)  it should be possible to upgrade the Sumo glibc recipe and build a new set of glibc packages from this repo. If you are really adventurous you can try the Dunfell branches but those are more on the "no guarantees" side being still under development.

[1] https://www.austingroupbugs.net/view.php?id=609
[2] https://github.com/dvhart/librtpi
[3] https://github.com/gratian/librtpi
[4] https://elinux.org/images/a/ae/Librtpi.pdf
[5] https://www.youtube.com/watch?v=lRUKrLZPgLM
[6] https://github.com/ni/openembedded-core/blob/nilrt/master/dunfell/meta/recipes-core/glibc/glibc_2.31.bb

**Comment by edbordin** [comment]
Thanks for the response, that explains a lot re: glibc! Since my last post I did manage to build a set of ipks for glibc 2.27 with the upstream sumo sources (figured this would be least likely to cause other build issues). The target seems to keep working fine with those installed on top of the stock 20.5 base image. Our application isn't hard real-time and we're using the DAQmx C API directly (hence the need for the SDK) so it looks workable so far.

I'm just working through some last issues when I build the full SDK with the newer glibc, happy to share what I find even if it's probably not applicable to most users. I'll edit the first post with an additional patch I needed to get it working which I forgot to include.

**Comment by gratian** [comment]
> Thanks for the response, that explains a lot re: glibc! Since my last post I did manage to build a set of ipks for glibc 2.27 with the upstream sumo sources (figured this would be least likely to cause other build issues). The target seems to keep working fine with those installed on top of the stock 20.5 base image. Our application isn't hard real-time and we're using the DAQmx C API directly (hence the need for the SDK) so it looks workable so far.

Glad to hear that. I agree, upgrading glibc like that should work for your use case.

> I'm just working through some last issues when I build the full SDK with the newer glibc, happy to share what I find even if it's probably not applicable to most users. I'll edit the first post with an additional patch I needed to get it working which I forgot to include.

Patches are always welcome. We take GitHub PRs too if you think it's something that's applicable to other users.

**Comment by amstewart** [comment]
Closing this issue, since it seems to have been resolved.
