### ISSUE TITLE
Error building minimal-nilrt-image

### ISSUE THREAD

**Issue by IndianaScarabee** [ni/nilrt#6]
Hi,

I am trying to build the minimal-nilrt-image but I get the error below :

ERROR: minimal-nilrt-image-1.0-r0 do_rootfs: Unable to install packages. Command '/home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/opkg.conf -t /home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/temp/ipktemp/ -o /home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install ni-sysmgmt-salt-minion-support nisdmon packagegroup-ni-base packagegroup-ni-tzdata opkg run-postinsts' returned 255:
Collected errors:
 * opkg_prepare_url_for_install: Couldn't find anything to satisfy 'ni-sysmgmt-salt-minion-support'.

ERROR: minimal-nilrt-image-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/temp/log.do_rootfs.4283
ERROR: Task (/home/pierre/Documents/nilrt-nilrt-18.0/sources/meta-nilrt/recipes-core/images/minimal-nilrt-image.bb:do_rootfs) failed with exit code '1'

Could you help me with this error.

Thanks.

**Comment by sharpk** [comment]
Hi, what branch are you building?

**Comment by IndianaScarabee** [comment]
I am building the nilrt/18.0 branch.

**Comment by sharpk** [comment]
I suspect the problem here is that minimal-nilrt-image is tied to a different distro configuration than you are using.  If you set up your environment with this command from the README: ''MACHINE=x64 DISTRO=nilrt ./nibb.sh config'' then you will get the error above.

If you set DISTRO to nilrt-nxg instead, then I believe the build should work.

**Comment by IndianaScarabee** [comment]
Thanks sharpk, it worked but I get a new error now.
I get the following error during the do_rootfs : 
ERROR: minimal-nilrt-image-1.0-r0 do_rootfs: Unable to update the package index files. Command '/home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/opkg.conf -t /home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/temp/ipktemp/ -o /home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   update' returned 6:
Collected errors:
 * opkg_download_file: ///home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/deploy/ipk/all/Packages.gz: No such file.
 * opkg_download_file: ///home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/deploy/ipk/x64/Packages.gz: No such file.
 * opkg_download_file: ///home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/deploy/ipk/core2-64/Packages.gz: No such file.
 * opkg_download_backend: Failed to download http://download.ni.com/ni-linux-rt/feeds/Cardassia/x64/ni/all/Packages.gz, wget returned 8.
 * opkg_download_backend: Failed to download http://download.ni.com/ni-linux-rt/feeds/Cardassia/x64/ni/x64/Packages.gz, wget returned 8.
 * opkg_download_backend: Failed to download http://download.ni.com/ni-linux-rt/feeds/Cardassia/x64/ni/core2-64/Packages.gz, wget returned 8.
 * rm_r: Failed to open dir /home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/work/x64-nilrt-linux/minimal-nilrt-image/1.0-r0/temp/ipktemp//opkg-im0TuQ: No such file or directory.
Downloading file:///home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/deploy/ipk/all/Packages.gz.
Downloading file:///home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/deploy/ipk/x64/Packages.gz.
Downloading file:///home/pierre/Documents/nilrt-nilrt-18.0/build/tmp_nilrt_nxg_3_0_x64-glibc/deploy/ipk/core2-64/Packages.gz.
Downloading http://download.ni.com/ni-linux-rt/feeds/Cardassia/x64/ni/all/Packages.gz.
Downloading http://download.ni.com/ni-linux-rt/feeds/Cardassia/x64/ni/x64/Packages.gz.
Downloading http://download.ni.com/ni-linux-rt/feeds/Cardassia/x64/ni/core2-64/Packages.gz.

It seems I can't update and download packages from http://download.ni.com/ni-linux-rt/feeds/Cardassia/x64/ni.

**Comment by sharpk** [comment]
I'm not surprised at this error, these images are not really appropriate for this branch.  So let's take a step back: what are you trying to accomplish?

Appropriate image recipes for this branch would be DISTRO=nilrt and valid image recipes are niconsole-image.bb and nixfce-image.bb.

**Comment by amstewart** [comment]
Closing historic and stale issues.
