### ISSUE TITLE
bitbake error: potential misconfiguration

### ISSUE THREAD

**Issue by MorjgusNI** [ni/nilrt#7]
I've checked out the nilrt/comms-2-0 branch nd followed the steps in the readme. After sourcing the oe environment I run bitbake and get the following error:

```
(bb) morjgus@morjgus-mint ~/Documents/projects/nilrt/build $ bitbake gcc
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Please install the following missing utilities: makeinfo,chrpath
libsdl-native is set to be ASSUME_PROVIDED but sdl-config can't be found in PATH. Please either install it, or configure qemu not to require sdl.

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

How can this issue be solved?

Regards,
Markus

**Comment by sharpk** [comment]
bitbake requires certain utilities to be present on your build system before it can run.  This error message is notifying you of those missing utils on your build machine (morjgus-mint).  It looks as if you need to install libsdl-dev (the package is libsdl1.2-dev on my system), and the packages which provide chrpath and makeinfo (texi2html on my system).

**Comment by amstewart** [comment]
Closing historic and stale issues.
