### ISSUE TITLE
ETA for 19.0?

### ISSUE THREAD

**Issue by ThadHouse** [ni/nilrt#8]
I noticed that packages for 2019 are posted on the NI packages feed, however a 19.0 version has not been posted to this repo. Our project uses this repo to build Mono, and it would be nice to get a head start on having the builds for the next image ready to go.

**Comment by amstewart** [comment]
We're prepping to push the 2019 sources now. I would expect they will all be available by the end of June. I'll close this issue as soon as they are available.

**Comment by amstewart** [comment]
@ThadHouse I've pushed the 2019 sources as the ``nilrt/19.0`` branch on nilrt.git and ``nilrt_pub/19.0/sumo`` on the associated OE meta layer repos.

Thanks for your interest. Marking this issue as closed.
