### ISSUE TITLE
Bitbake problem for building bootable recovery disk 21.0 for ARM

### ISSUE THREAD

**Issue by sighaderi** [ni/nilrt#83]
Hi,
I installed a fresh copy of "Ubuntu 20.04.3 LTS" and then added this packages :

     $ sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
     xz-utils debianutils iputils-ping libsdl1.2-dev xterm

I followed the instructions for 21.0 release (git checkout nilrt/21.0/sumo) for ARM target (export MACHINE=xilinx-zynq) but I have errors in step 3 ...

I only need "Bootable recovery disk 21.0 for ARM"
Thank you very much if anyone can give me the ready to use iso file

**Comment by chaitu236** [comment]
Hi,

The directions here for building recovery image are for x64 targets and don't apply to ARM targets.

A recovery image has to be obtained from NI directly for the specific model of cRIO you have.
Please raise a service request with NI ([link](https://sine.ni.com/srm/app/myServiceRequests)) and mention the cRIO model you have to receive it.

[Here](https://forums.ni.com/t5/Real-Time-Measurement-and/Unable-to-access-or-format-cRIO-9068/td-p/3773268?profile.language=en) is a thread that discusses recovering an ARM cRIO that you may also find helpful.

**Comment by chaitu236** [comment]
I hope this answers your question and we're going to close this issue. If it doesn't, feel free to reopen.
