### ISSUE TITLE
bitbake fatal, outdated?

### ISSUE THREAD

**Issue by martiinz** [ni/nilrt#9]
When following the Readme for 17.0, I got following error
``` bash
| DEBUG: Running export DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-m5Wkks09pt,guid=41fadb0808b6f534efb4ba5c5e84532e"; export SSH_AGENT_PID="1672"; export SSH_AUTH_SOCK="/tmp/ssh-t1ugOLz6EaGv/agent.1592"; export PATH="/home/mas/nilrt/sources/openembedded-core/scripts/native-intercept:/home/mas/nilrt/sources/openembedded-core/scripts:/home/mas/nilrt/build/tmp_nilrt_3_0_xilinx-zynq-glibc/sysroots/x86_64-linux/usr/bin/x86_64-linux:/home/mas/nilrt/build/tmp_nilrt_3_0_xilinx-zynq-glibc/sysroots/x86_64-linux/usr/bin:/home/mas/nilrt/build/tmp_nilrt_3_0_xilinx-zynq-glibc/sysroots/x86_64-linux/usr/sbin:/home/mas/nilrt/build/tmp_nilrt_3_0_xilinx-zynq-glibc/sysroots/x86_64-linux/usr/bin:/home/mas/nilrt/build/tmp_nilrt_3_0_xilinx-zynq-glibc/sysroots/x86_64-linux/sbin:/home/mas/nilrt/build/tmp_nilrt_3_0_xilinx-zynq-glibc/sysroots/x86_64-linux/bin:/home/mas/nilrt/sources/openembedded-core/scripts:/home/mas/nilrt/sources/bitbake/bin:/home/mas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"; export HOME="/home/mas"; git -c core.fsyncobjectfiles=0 branch --set-upstream master origin/master
| DEBUG: Python function base_do_unpack finished
| DEBUG: Python function do_unpack finished
| ERROR: Function failed: Fetcher failure: Fetch command failed with exit code 128, output:
| fatal: the '--set-upstream' option is no longer supported. Please use '--track' or '--set-upstream-to' instead.
| 
ERROR: Task 88 (virtual:native:/home/mas/nilrt/sources/openembedded-core/meta/recipes-devtools/gnu-config/gnu-config_git.bb, do_unpack) failed with exit code '1'
```
I'm on ubuntu 18.04 and git 2.17.1 installed
The command `git -c core.fsyncobjectfiles=0 branch --set-upstream master origin/master` fails, cause ` the '--set-upstream' option is no longer supported`.

Looks for me, that [ni/bitbake](https://github.com/ni/bitbake) is outdated. Any way to update that? or change source to original repo?

**Comment by shruthi-ravi** [comment]
The [bitbake branch](https://github.com/ni/nilrt/blob/nilrt/17.0/sources/layers.txt#L1) in nilrt/17.0 is very old and has a bitbake version that uses the `--set-upstream` option, which is no longer supported by git.
Is there a reason you are working off of the nilrt/17.0 branch? Could you update that to the latest nilrt/19.1? That will get you the [latest bitbake](https://github.com/ni/nilrt/blob/nilrt/19.1/sources/layers.txt#L1), which includes changes to use `--set-upstream-to` instead of `--set-upstream`.

**Comment by martiinz** [comment]
Ok, thank you for confirming!
Well, my intention was to support LV17 and LV19 for our product.
I will go for 19 first and might try to update the 17 bitbake layer...
