### ISSUE TITLE
Linux containers fails to download

### ISSUE THREAD

**Issue by bertg42** [ni/nilrt#96]
The linux container project has changed their download location.
Previous: https://linuxcontainers.org/downloads/
Current: https://linuxcontainers.org/lxc/downloads/

**Comment by amstewart** [comment]
I assume you're trying to build the `lxc` recipe in sumo here.

That recipe is also in the extras feed that is presented 'as-is'. So it isn't surprising to me that it has broken without us noticing. Do you have a use-case that you require LXC for?

FYI for anyone who wants an immediate solution here: upstream meta-virtualization commit [55b5e02d067b8d6f59397a3ea49bd3139d544445](https://git.yoctoproject.org/meta-virtualization/commit/recipes-containers/lxc?id=55b5e02d067b8d6f59397a3ea49bd3139d544445) applies the fix to the `4.0.6` version of the recipe. You'll need to cherry-pick the recipe commits between the sumo version of the recipe and - at least - that commit.

**Comment by amstewart** [comment]
@bertg42 and I have discussed offline and determined that (a) he doesn't need this recipe for his project and (b) this recipe isn't in the short-list of supported packages from NI. For those reasons, we're closing this issue.
